### ISSUE TITLE
Notes on program space

### ISSUE THREAD

**Issue by elovejoy-nyle** [FOSSBOSS/PLC2C#1]
Your notes on program space aren't wrong, but are incomplete. Program space is indeed on one line, 
but the rung comments, device labels, and device tags, are successively on one line as well. 
Seems to go something like: 
0A Rung comments
0A device Tags
0A program space
0A device labels. 
0A Character flags

If i had to guess, I would think there is some pattern in line length. Maybe add functionality to deconstructPJW.py to disassemble the LDR component as well.

**Comment by FOSSBOSS** [comment]
yep. Having more complex programs to develop this program based on has been eye opening. 
the memory addresses of devices was the first thing I figured out, but then after looking at more complex programs, and object usage I was able to determine all the consequential subsections, and that the other devices are essentially labels.
things like SOTU, SOTO, AND,NOR.... these are also noted in the IDEC documentation, though not from the de-compilation perspective, the tags are all still there.
